name: Build and push binary
on: workflow_dispatch

jobs:
  Build-and-push:
    name: Build and push binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build
        shell: bash
        run: |
          npm install
          npm run build

      - name: Push
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git diff --name-only
          git add dist/index.js
          git commit -m "[Bot] Update pre-built binary"
          git push
